name: google document copy

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  copy_google_doc:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install packages for work
        run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: save credential
        run: echo '${{ secrets.GOOGLE_CREDENTIALS }}' > ${{ github.workspace }}/google_auto/credentials.json

      - name: Configure source folder ID
        run: sed -i "s|REPLACE_WITH_YOUR_DOCUMENT_SOURCE_FOLDER_ID|${{ secrets.DOCUMENT_SOURCE_FOLDER_ID }}|g" ${{ github.workspace }}/google_auto/config.json

      - name: execute to copy Google Document
        run: python google_document/refactored_copy_document_report.py
        working-directory: ${{ github.workspace }}/google_auto