name: Web Scraping and Slack Notification

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

env:
  WORKING_DIR: ${{ github.workspace }}

jobs:
  scraping:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run the scraper
        id: run_scraper
        run: |
          RESULT=$(python ${{ env.WORKING_DIR }}/gunpla/notif-mg-gunpla-info.py)
          echo "RESULT_CONTENT<<EOF" >> $GITHUB_ENV
          echo "$RESULT" | sed ':a;N;$!ba;s/\n/\\n/g' >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send notification to Slack
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.GUNPLA_SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "スクレイピングが完了しました。\n結果:\n${{ env.RESULT_CONTENT }}"
                  }
                }
              ]
            }
